minimum_pre_commit_version: '3.5.0'
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: ['--fix']
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        stages: [push]
        additional_dependencies: [types-requests]
        args:
          - --cache-dir=.mypy_cache
          - --warn-unused-configs
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --no-warn-no-return
          - src
          - tests
          - scripts
        pass_filenames: false

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        stages: [push]
        args: ['-r', 'src/', 'scripts/']

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        name: pip-audit (manual)
        stages: [manual]
        args: ['--requirement', 'requirements.txt', '--requirement', 'requirements-dev.txt']

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        stages: [manual]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables

default_stages: [commit, push]

exclude: |
  (?x)^(
    \.git/.*|
    \.venv/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    htmlcov/.*|
    \.coverage.*|
    build/.*|
    dist/.*|
    \.egg-info/.*
  )$
