# Pre-commit configuration for Twitch ColorChanger Bot
# Modern approach using Ruff for fast, comprehensive Python linting and formatting

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: Trim trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: check-yaml
        description: Check YAML files for syntax errors
      - id: check-json
        description: Check JSON files for syntax errors
      - id: check-toml
        description: Check TOML files for syntax errors
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-added-large-files
        description: Prevent large files from being committed
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        description: Ensure consistent line endings
        args: ['--fix=lf']

  # Ruff - Fast Python linter and formatter (replaces flake8, isort, autopep8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      # Ruff linter
      - id: ruff
        args: [
          '--fix',           # Automatically fix fixable violations
          '--exit-non-zero-on-fix'  # Exit with non-zero code if fixes were applied
        ]
      # Ruff formatter (replaces Black)
      - id: ruff-format

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        description: Type check Python code with mypy
        additional_dependencies: [types-requests]
        args: ['--ignore-missing-imports']

  # Security scanning
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        description: Security linting with Bandit
        args: ['-r', 'src/']
        exclude: ^tests/
        additional_dependencies: [pbr]

  # Custom hook to run our comprehensive lint command
  - repo: local
    hooks:
      - id: make-lint
        name: Run make lint
        entry: make
        args: [lint]
        language: system
        description: Run comprehensive linting with make lint
        pass_filenames: false
        always_run: true
        stages: [commit]

# Configure which hooks run at which stages
default_stages: [commit]

# Exclude certain files/directories
exclude: |
  (?x)^(
    \.git/.*|
    \.venv/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    htmlcov/.*|
    \.coverage.*|
    build/.*|
    dist/.*|
    \.egg-info/.*
  )$
