# Pre-commit configuration for Twitch ColorChanger Bot
# See https://pre-commit.com for more information

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: Trim trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with a newline
      - id: check-yaml
        description: Check YAML files for syntax errors
      - id: check-json
        description: Check JSON files for syntax errors
      - id: check-toml
        description: Check TOML files for syntax errors
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-added-large-files
        description: Prevent large files from being committed
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        description: Ensure consistent line endings
        args: ['--fix=lf']

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        description: Format Python code with Black
        language_version: python3
        args: ['--line-length=88']

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: Sort Python imports
        args: ['--profile=black', '--line-length=88']

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        description: Lint Python code with flake8
        args: ['--max-line-length=88', '--ignore=E203,W503,E501']

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        description: Type check Python code with mypy
        additional_dependencies: [types-requests]
        args: ['--ignore-missing-imports']

  # Security scanning
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        description: Security linting with Bandit
        args: ['-r', 'src/']
        exclude: ^tests/
        additional_dependencies: [pbr]

  # Custom hook to run our comprehensive lint command
  - repo: local
    hooks:
      - id: make-lint
        name: Run make lint
        entry: make
        args: [lint]
        language: system
        description: Run comprehensive linting with make lint
        pass_filenames: false
        always_run: true
        stages: [commit]

# Configure which hooks run at which stages
default_stages: [commit]

# Exclude certain files/directories
exclude: |
  (?x)^(
    \.git/.*|
    \.venv/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    htmlcov/.*|
    \.coverage.*|
    build/.*|
    dist/.*|
    \.egg-info/.*
  )$
