codecov:
  notify:
    after_n_builds: 1
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        informational: false
      unittests:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%
      unittests:
        target: 100%
        threshold: 0%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests"  # Already excluded in coverage.py, but keep explicit here

flags:
  unittests:
    joined: true
    paths:
      - src
    carryforward: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

github_checks:
  annotations: true
